name: Build & Run all tests (release)

on:
    push:
    pull_request:
    workflow_dispatch:
    
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: cmd

jobs:
    
    build-latest:
        name: .Net Framework - Latest
        runs-on: windows-2019
        steps:
          - uses: actions/checkout@v4
          
          - name: Setup MSBuild
            uses: microsoft/setup-msbuild@v1
          
          - name: Install dependencies into Virtual Environment...
            run: _RegisterHelixNUnit.bat
          
          - name: Build project in Release-mode, compile Pas-units, run tests
            run: _RebuildReleaseAndRunTestsForGitHubActions.bat
            timeout-minutes: 40
            env:
                REBUILD_PAS_FILE: RebuildStandartModules.pas
    
    build-WinXP:
        name: .Net Framework 4.0
        runs-on: windows-2019
        steps:
          - uses: actions/checkout@v4
          
          - name: Setup MSBuild
            uses: microsoft/setup-msbuild@v1
          
          - name: Setup .NET Framework 4.0
            run: choco install dotnet4.0 -y
          
          - name: Install dependencies into Virtual Environment...
            run: _RegisterHelixNUnit.bat
          
          - name: Build project in Release-mode, compile Pas-units, run tests
            run: _RebuildReleaseAndRunTestsForGitHubActions.bat
            timeout-minutes: 40
            env:
                REBUILD_PAS_FILE: RebuildStandartWinXPModules.pas
    