name: Build & Run all tests (release) & Make an unstable release

on:
  push:

  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

defaults:
  run:
    shell: cmd

jobs:
    build:
    
        name: Prepare and build on Windows Server 2016 VM
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies into Virtual Environment...
              run: _RegisterHelixNUnit.bat

            - name: Build project in Release-mode, compile Pas-units, run tests
              run: _GenerateAllSetupsForGitHubActions.bat
              timeout-minutes: 40
              env:
                PABCNET_BUILD_MODE: Release
                PABCNET_RUN_TESTS:  false
                PABCNET_INC_BUILD:  false
                PABCNET_VERBOSE:    false

            - name: Create Github Release
              uses: actions/github-script@v6
              with:
                script: |
                
                    console.log('environment', process.versions);

                    const { repo: { owner, repo }, sha } = context;
                    console.log({ owner, repo, sha });

                    const tag = "unstable";

                    // Check if the release already exists
                    const existingReleases = await github.rest.repos.listReleases({ owner, repo });
                    for (const existingRelease of existingReleases.data) {
                        if (existingRelease.tag_name === tag) {
                            console.log('deleing old release', { existingRelease });
                            await github.rest.repos.deleteRelease({
                                owner,
                                repo,
                                release_id: existingRelease.id,
                            });
                            break;
                        }
                    }

                    try {
                        await github.rest.git.deleteRef({
                            owner: owner,
                            repo: repo,
                            ref: 'tags/unstable'
                        });
                        console.log('Tag deleted successfully');
                    } catch (error) {
                        console.error(`Error deleting tag: ${error}`);
                    }

                    const fs = require('fs').promises;

                    const release = await github.rest.repos.createRelease({
                        owner, repo,
                        tag_name: tag,
                        name: "Custom unstable build",
                        draft: true,
                        prerelease: true,
                        target_commitish: sha
                    });

                    console.log('created release', { release });

                    for (let file of await fs.readdir('Release')) {
                        console.log('uploading', file);

                    try {
                        await github.rest.repos.uploadReleaseAsset({
                            owner, repo,
                            release_id: release.data.id,
                            name: file,
                            data: await fs.readFile(`./Release/${file}`)
                        });
                    } catch (error) {
                        console.error(`Error uploading: ${error}`);
                    }

                    }

                    if (release.data.draft) {
                        console.log('finalizing draft release');
                        await github.rest.repos.updateRelease({
                            owner,
                            repo,
                            release_id: release.data.id,
                            draft: false,
                        });
                    }
                    
    Trigger-dependant-rep-actions:
        runs-on: ubuntu-latest
        needs: [build]
        
        steps:
            - uses: actions/github-script@v5
              with:
                github-token: ${{ secrets.PAT_TOKEN }}
                script: |
                
                    if (false) await github.rest.actions.createWorkflowDispatch({
                        owner: 'SunSerega',
                        repo: 'POCGL',
                        workflow_id: 'on commit.yaml',
                        ref: 'stable',
                    });
                    await github.rest.actions.createWorkflowDispatch({
                        owner: 'SunSerega',
                        repo: 'POCGL',
                        workflow_id: 'on commit.yaml',
                        ref: 'unstable',
                    });
                    